services:
  api:
    container_name: helmies-studio-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
      - meilisearch
    restart: always
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/HelmiesStudio
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - DOMAIN_CLIENT=${DOMAIN_CLIENT:-http://localhost:3080}
      - DOMAIN_SERVER=${DOMAIN_SERVER:-http://localhost:3080}
      - PORT=${PORT:-3080}
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    env_file:
      - .env

  mongodb:
    container_name: helmies-studio-mongodb
    image: mongo:8.0.20
    restart: always
    volumes:
      - mongo-data:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: helmies-studio-meilisearch
    image: getmeili/meilisearch:v1.35.1
    restart: always
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - meili-data:/meili_data

volumes:
  mongo-data:
  meili-data:
